### ISSUE TITLE
PlayList Page 

### ISSUE THREAD

**Issue by gyeongwon1275** [gyeongwon1275/music-player#4]
### Situation 

- [ ] 사용자는 local 에서 음악파일을 playlist 에 추가할 수 있다. 
- [ ] 사용자는 추가된 음악파일 목록을 확인할 수 있다. 
- [ ] 사용자는 horizontal menu icon 을 통해 파일을 즐겨찾기에 추가하거나 playlist 에서 삭제할 수 있다. 
- [ ] Drag& Drop 으로 file 을 upload 할 수 있다. 
<img width="279" alt="스크린샷 2022-04-04 오후 2 00 47" src="https://user-images.githubusercontent.com/60727230/161478742-9d0c62ef-e1cd-4f8e-be88-668ec5651758.png">

### Task 

- [ ] PlayList.ts 에서 BottomNavigation, MusicList 관리
- [ ] data, 이벤트리스너는 PlayList 에서 하위 컴포넌트로 prop 으로 넘김

MusicList
- [ ] UI 를 customElement 로 제작
- [ ] ul 에 event 위임 설정, li 클릭 되면 해당 li aria-selected : true 로 변경

### Action

- [ ]
